### ISSUE TITLE
geth传数据到kafka中endpoint问题

### ISSUE THREAD

**Issue by xingyushu** [jdcloud-bds/bds-etc#3]
Geth | Kafka | Go
-- | -- | --
... | 2.1.1 | 1.12.7

我是在docker里运行的kafka,然后配置的是9092端口  
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.18.129
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /data/product/zj_bigdata/data/kafka/docker.sock:/var/run/docker.sock
```
我是这样设置的参数，将eth的区块节点数据发送到kafka

`geth --datadir  ./chaindata/  --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 --cache 100 --rpc --rpccorsdomain --kafka.endpoint "http://localhost:9092"`

提示参数配置错误：
`invalid command: "url=http://localhost:9092"`

我应该怎么配置kafka的参数才能发送成功到kafka中去呢  

省略后面自定义的url能同步成功吗，怎么验证
